# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-04-28 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EggSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=50)),
                ('id_dark_spots', models.SmallIntegerField(max_length=10)),
                ('spot_num', models.IntegerField(max_length=255)),
                ('spot_square', models.FloatField(max_length=255)),
            ],
        ),
    ]
